import React from 'react';
import './globals.css';

import { Inter } from 'next/font/google';
import Providers from './providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'eCom | NextJS e-commerce store',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} w-screen`}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
