import React from 'react';
import './globals.css';

import { Inter } from 'next/font/google';
import Providers from './providers';
import Header from '../components/Header/Header';
import Banners from '../components/Banners/Banners';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'eCom | NextJS e-commerce store',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <Providers>
          <Header />
          <Banners />
          <main className="flex min-h w-full relative flex-col items-center justify-center p-3">
            <div className="w-full max-w-[1440px] flex flex-col gap-4">
              {children}
            </div>
          </main>
          {/* <Footer /> */}
        </Providers>
      </body>
    </html>
  );
}
